use std::error::Error;

mod day_01;
mod day_02;

fn main() -> Result<(), Box<dyn Error>> {
    //day_01::run()
    //day_02::part_1();
    day_02::part_2()
}